# Generated by Django 4.2.13 on 2024-05-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunter_app', '0003_produto_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='mensagem',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='titulo',
        ),
    ]
