# Generated by Django 5.0.6 on 2024-05-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunter_app', '0004_rename_message_contact_mensagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(upload_to=''),
        ),
    ]
